name: rt-prediction
dependencies:
  - python=3.8
  - pip
  - pip:
    - torch
    - torch-geometric
    - rdkit
    - scikit-learn
    - gpytorch
    - matplotlib
    - seaborn
    - tqdm
    - pyyaml
    - pytest
    - jupyter
